### ISSUE TITLE
using paths over instead of transport

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#28]
Perhaps I can rewrite this to use a path over instead of transport.  If not, at least refer to the appropriate statement about paths between pairs.

<img width="664" alt="Screen Shot 2019-03-29 at 4 56 43 PM" src="https://user-images.githubusercontent.com/700228/55245623-c735f780-5243-11e9-9b4d-3c512fa37b78.png">

**Comment by DanGrayson** [comment]
Egbert has an idea about how to say this he can explain to us.  I've assigned the issue to him.

**Comment by marcbezem** [comment]
I think it is hard to completely avoid transport in relation to paths over, but in this case there is an elegant way to hide transport in cast. Let toA be the type family _ -> A, that is, toA(Z) := Z -> A. For all types X,Y, path p: X=Y and functions f: X->A, g: Y->A, the path over type f =_p^toA g is equal to the type f = g o fst(cast(p)). Proof: induction on p. QED

It does the job since cast(ua(e)) = e, so that the type becomes fst = f o e. 
If you like this I can rewrite.

**Comment by marcbezem** [comment]
I actually implemented this, please take a look.

**Comment by DanGrayson** [comment]
Looks fine, closing.
