### ISSUE TITLE
tiny subscript nearly illegible

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#88]
My eyes can't really make out the tiny subscript on the BF here:
<img width="672" alt="Screen Shot 2020-08-10 at 7 30 39 AM" src="https://user-images.githubusercontent.com/700228/89778439-257b1780-dad3-11ea-96c1-e24134d3c04e.png">

**Comment by marcbezem** [comment]
I have no objection to slightly enlarge it, and Pierre is the most competent one to do that.
It should, however, not become footnote size, as that was ugly and distracting.
After all, we allow to leave it out, so the problem is that if you don't see it clearly, you don't recognize it as something that could be left out, and you are left with the worry that you may miss something. Modern lingo for this mental condition seems to be FOMO (fear of missing out :-)
