### ISSUE TITLE
"nothing but"

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/SymmetryBook#9]
We should reserve the phrase "nothing but" for judgmental equalities, not equivalences, as here:

<img width="684" alt="screen shot 2019-02-27 at 3 07 15 pm" src="https://user-images.githubusercontent.com/700228/53496035-78a90800-3aa1-11e9-8b8a-4be5b1c48dad.png">

**Comment by marcbezem** [comment]
Do you mean: "the truth and nothing but the truth" should be judgementally equal to the unit type? :-)

**Comment by DanGrayson** [comment]
Yes, provided you have η-reduction for the the unit type.

**Comment by bidundas** [comment]
the issue here is not so much what greek letter to use.  Rather, we should choose between "G-set X:BG-> Set" and  "set map X:BG->Set".  I am partial to the former, and (but) has the (dis)advantage that it is impossible to talk about these without specifying G, which becomes slightly awkward in the circle chapter (before we've defined groups)

**Comment by DanGrayson** [comment]
Thanks, closing.
